server {
    listen 80;
    server_name _;

    # ── React Dashboard ──
    location / {
        proxy_pass http://react:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # ── API Laravel ──
    location /api/ {
        proxy_pass http://laravel:8000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_read_timeout 90;
    }

    # ── phpMyAdmin ──
    location /phpmyadmin/ {
        proxy_pass http://phpmyadmin:80/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}